export const GREETINGS = [
  "Hi",
  "Hello",
  "Hey",
  "Hey there",
  "Hiya",
  "Heya",
  "Hi there",
  "Hello there",
  "Greetings",
  "Welcome back",
  "Welcome",
  "Howdy",
  "Howdy do",
  "Howdy partner",
  "What's up",
  "What's good",
  "What's happening",
  "Welcome home",
  "Yo",
  "Sup",
  "Wassup",
  "Hi-ho",
  "Good day",
  "Salutations",
  "Cheers",
  "Ahoy",
  "Holler",
  "G'day",
  "Cheerio",
  "Eh",
  "Showtime",
  "Sound check",
  "Encore",
  "Rock on",
  "Good morning",
  "Good afternoon",
  "Good evening",
  "Hola",
  "Buenos días",
  "Buenas tardes",
  "Buenas noches",
  "¿Qué tal?",
  "¿Qué pasa?",
  "Saludos",
  "Buenas",
  "Bonjour",
  "Salut",
  "Bonsoir",
  "Coucou",
  "Allô",
  "Ciao",
  "Buongiorno",
  "Buonasera",
  "Salve",
  "Hallo",
  "Guten Tag",
  "Servus",
  "Moin",
  "Olá",
  "Bom dia",
  "Tudo bem",
  "Konnichiwa",
  "Ohayō",
  "Yāhō",
  "Annyeong",
  "Annyeong haseyo",
  "Nǐ hǎo",
  "Hāi",
  "Namaste",
  "Namaskar",
  "Pranam",
  "Shalom",
  "Marhaba",
  "Salaam",
  "Ahlan",
  "Privet",
  "Hej",
  "Hei",
  "Yassou",
  "Merhaba",
  "Sawubona",
  "Mabuhay",
  "The Legend",
  "The Myth",
  "OMG IT'S",
  "WOW IT'S",
  "I Love",
  "We Love",
  "Everybody Loves",
  "The Great",
  "Here Comes",
  "My Friend",
  "The Amazing",
  "Marry Me",
] as const;

/** Returns one greeting at random. Safe to call in server components — runs server-side. */
export function getRandomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)] as string;
}
