export const AREAS_OF_LAW = [
  "Administrative Law",
  "Antitrust",
  "Bankruptcy",
  "Business Associations",
  "Civil Procedure",
  "Civil Rights",
  "Constitutional Law",
  "Contracts",
  "Copyright",
  "Criminal Law",
  "Criminal Procedure",
  "Employment / Labor Law",
  "Entertainment Law",
  "Environmental Law",
  "Estate Planning / Trusts & Estates",
  "Evidence",
  "Family Law",
  "Health Law",
  "Immigration",
  "Intellectual Property (Survey)",
  "International Law",
  "Legal Ethics",
  "Legal Writing & Research",
  "Negotiation",
  "Patents",
  "Privacy / Data Protection",
  "Product Liability",
  "Property",
  "Real Estate",
  "Right of Publicity",
  "Securities Regulation",
  "Sports Law",
  "Tax",
  "Torts",
  "Trademark",
  "Trial Advocacy",
] as const;

export type AreaOfLaw = (typeof AREAS_OF_LAW)[number];
