-- IRS EIN Wizard: ein_applications session table.
-- Phase IRS-W-DB. Date: 2026-05-08.
--
-- Persists multi-step EIN application data across the wizard chain:
--   landing → legal_structure → identity → address →
--   additional_details_1 → additional_details_2 → review → submitted
--
-- Mirrors the filing_sessions pattern (20260507m_filing_sessions.sql, commit b823dff):
--   • jsonb form_data for flexible per-step field accumulation
--   • Permanent rows (no DELETE policy) for audit log
--   • Auto-updating last_saved_at trigger
--   • RLS: users see/edit only their own sessions
--
-- form_data keys are discovered per wizard step in W1–W5 (legal_structure,
-- responsible_party_name, address_line_1, etc.). Schema is flexible at this
-- layer; W-step implementations constrain field names in application code.

-- ─── Table ────────────────────────────────────────────────────────────────────

CREATE TABLE public.ein_applications (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  current_step  text        NOT NULL DEFAULT 'landing'
                            CHECK (current_step IN (
                              'landing',
                              'legal_structure',
                              'identity',
                              'address',
                              'additional_details_1',
                              'additional_details_2',
                              'review',
                              'submitted',
                              'abandoned'
                            )),
  status        text        NOT NULL DEFAULT 'in_progress'
                            CHECK (status IN (
                              'in_progress',
                              'submitted',
                              'abandoned'
                            )),
  form_data     jsonb       NOT NULL DEFAULT '{}'::jsonb,
  -- keyed by IRS field names (legal_structure, responsible_party_name,
  -- address_line_1, etc.) discovered per step in W1–W5.
  ein_assigned  text,
  -- final EIN in XX-XXXXXXX format; null until receipt page (W6) finalizes.
  started_at    timestamptz NOT NULL DEFAULT timezone('utc', now()),
  last_saved_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  submitted_at  timestamptz
);

COMMENT ON TABLE  public.ein_applications IS
  'Multi-step IRS EIN application session state. One row per in-progress or completed wizard attempt. Permanent (no DELETE) per audit-log requirement — mirrors filing_sessions.';

COMMENT ON COLUMN public.ein_applications.id           IS 'Primary key — UUID generated by the database.';
COMMENT ON COLUMN public.ein_applications.user_id      IS 'FK to auth.users; the applicant who owns this session.';
COMMENT ON COLUMN public.ein_applications.current_step IS 'Last wizard step the user reached: landing, legal_structure, identity, address, additional_details_1, additional_details_2, review, submitted, abandoned.';
COMMENT ON COLUMN public.ein_applications.status       IS 'Lifecycle state: in_progress, submitted, abandoned.';
COMMENT ON COLUMN public.ein_applications.form_data    IS 'All form values accumulated across wizard steps, keyed by IRS-style field name (legal_structure, responsible_party_name, address_line_1, etc.).';
COMMENT ON COLUMN public.ein_applications.ein_assigned IS 'EIN issued at receipt step, in XX-XXXXXXX format. Null until the application is submitted and finalized.';
COMMENT ON COLUMN public.ein_applications.started_at   IS 'Timestamp when the wizard session was created (UTC).';
COMMENT ON COLUMN public.ein_applications.last_saved_at IS 'Timestamp of last write — auto-updated by trigger on every UPDATE.';
COMMENT ON COLUMN public.ein_applications.submitted_at  IS 'Timestamp when status was set to submitted. Null until finalized.';

-- ─── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX idx_ein_applications_user_id
  ON public.ein_applications (user_id);

CREATE INDEX idx_ein_applications_status
  ON public.ein_applications (current_step, status);

-- ─── Row Level Security ───────────────────────────────────────────────────────

ALTER TABLE public.ein_applications ENABLE ROW LEVEL SECURITY;

-- Users see only their own applications
CREATE POLICY "ein_applications_select_own"
  ON public.ein_applications
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users insert applications as themselves
CREATE POLICY "ein_applications_insert_own"
  ON public.ein_applications
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users update their own in-progress applications only
CREATE POLICY "ein_applications_update_own"
  ON public.ein_applications
  FOR UPDATE
  USING  (auth.uid() = user_id AND status = 'in_progress')
  WITH CHECK (auth.uid() = user_id);

-- No DELETE policy — applications are permanent audit records.

-- ─── Trigger: auto-update last_saved_at on every UPDATE ──────────────────────

CREATE OR REPLACE FUNCTION public.touch_ein_application_last_saved()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.last_saved_at := now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.touch_ein_application_last_saved IS
  'Keeps ein_applications.last_saved_at current on every UPDATE. Mirrors touch_filing_session_last_saved.';

CREATE TRIGGER touch_ein_application_last_saved
  BEFORE UPDATE ON public.ein_applications
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_ein_application_last_saved();
